services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - backend
      - geodesic
    environment:
      - BACKEND_URL=http://backend:8080 

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    networks:
      - back-tier
    depends_on:
      geodesic:
        condition: service_started
    environment:
      - GEODESIC_URL=http://geodesic:8000
  geodesic:
    build:
      context: ./geodesic
      dockerfile: Dockerfile
    networks:
      - back-tier

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagedb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL","pg_isrady -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  data:
    build:
      context: ./data
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - back-tier
    environment:
      DATA_URL: http://data:8081
      DATABASE_URL: postgresql://postgres:postgres@postgres:5433/imagedb

volumes:
  postgres_data:

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge