[project]
name = "back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.129.0",
    "httpx[standard]>=0.28.1",
    "requests[standard]>=2.32.5",
]
